In [1]:
import pandas as pd

xls = pd. ExcelFile(r'dataset2.xlsx')
df1 = pd. read_excel(xls, 'Sales')
df2 = pd. read_excel(xls, 'Stocks')

df1

,Date,Week,sku,Sales_Count
0,2020-06-06,24,أرز حبوبة رفيع - 1 كيلو,69
1,2020-06-06,24,زيت كريستال ذرة ( 6 أزازة ) - 2.4 لتر,17
2,2020-06-06,24,زيت كريستال عباد الشمس ( 6 أزازة ) - 2.4 لتر,14
3,2020-06-06,24,زيت كريستال الممتاز خليط - 1 لتر,7
4,2020-06-06,24,سكر الأهرام - 1 كيلو,78
...,...,...,...,...
6541,2020-06-15,25,شاى ليبتون أخضر بدون مرارة (عرض) - 25 فتلة,74
6542,2020-06-15,25,شويبس رمان كانز - 300 مل,79
6543,2020-06-15,25,شويبس جولد أناناس كانز - 300 مل,44
6544,2020-06-15,25,حفاضات مولفيكس (58) عرض - 4 مقاس,2
6545,2020-06-15,25,حفاضات مولفيكس (58) عرض - 3 مقاس,1

In [9]:
df2.head()

                                            sku  Stock
0                       أرز حبوبة رفيع - 1 كيلو   1395
1         زيت كريستال ذرة ( 6 أزازة ) - 2.4 لتر     58
2  زيت كريستال عباد الشمس ( 6 أزازة ) - 2.4 لتر     43
3              زيت كريستال الممتاز خليط - 1 لتر     47
4                          سكر الأهرام - 1 كيلو   1757

# Number 7

In [48]:
df3 = df1.groupby(by=['sku'])['sku','Sales_Count'].sum()
df3.sort_values(by=['Sales_Count'], ascending=False)

<ipython-input-48-cdbded38ee5a>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df3 = df1.groupby(by=['sku'])['sku','Sales_Count'].sum()

                                           Sales_Count
sku
لمبادا دوبل اكسترا محشو شوكولاته - 2 جنية         5198
تونة صن شاين قطع أزرق - 185 جرام                  3677
سكر شهد - 1 كيلو                                  2857
تونة صن شاين مفتتة أخضر - 185 جرام                2750
بيبسي - 1.25 لتر                                  2571
...                                                ...
عسل أبيض نوارة البرسيم هيرو - 650 جرام               1
سمنة الشمس الذهبية أبيض - 1.45 كيلو                  1
مكرونة فرن بارما - 500 جرام                          1
عصير كل يوم كوكتيل - 180 مل                          1
بيرسول بلس - 300 مل                                  1

[897 rows x 1 columns]

In [49]:
df4 = df2.groupby(by=['sku'])['sku','Stock'].sum()
df4.sort_values(by=['Stock'], ascending=False)

<ipython-input-49-8259195b152b>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df4 = df2.groupby(by=['sku'])['sku','Stock'].sum()

                                            Stock
sku
تونة صن شاين قطع أزرق - 185 جرام            93528
تونة صن شاين مفتتة أخضر - 185 جرام          89352
مرقة دجاج ماجي شريط - 8 جرام                62028
كوفي ميكس بونجورنو ظرف - 12 جرام            59526
تونة صن شاين قطعة واحدة برتقالي - 200 جرام  59364
...                                           ...
بيرسول بلس - 300 مل                             1
ذره فيشار حبة حبة  - 500 جرام                   1
تاوتاو كيك محشو مربي الحليب - 2 جنية            1
كيلوجز سوبر باك بنكهة الخضار - 120 جرام         1
كيلوجز سوبر باك بنكهة الدجاج - 120 جرام         1

[897 rows x 1 columns]

In [57]:
averagepersku = df4.assign(AverageInventory = (df4['Stock'] + df3['Sales_Count']) / 2)
averagepersku.sort_values(by=['AverageInventory'], ascending=False)

                                            Stock  AverageInventory
sku
تونة صن شاين قطع أزرق - 185 جرام            93528           48602.5
تونة صن شاين مفتتة أخضر - 185 جرام          89352           46051.0
مرقة دجاج ماجي شريط - 8 جرام                62028           31517.5
تونة صن شاين قطعة واحدة برتقالي - 200 جرام  59364           30765.5
كوفي ميكس بونجورنو ظرف - 12 جرام            59526           30608.5
...                                           ...               ...
مسحوق أريال أوتوماتيك ألوان - 2.5 كيلو          2               1.5
كيلوجز سوبر باك بنكهة الدجاج - 120 جرام         1               1.0
ذره فيشار حبة حبة  - 500 جرام                   1               1.0
كيلوجز سوبر باك بنكهة الخضار - 120 جرام         1               1.0
بيرسول بلس - 300 مل                             1               1.0

[897 rows x 2 columns]

In [68]:
DOH = averagepersku.assign(DaysOnHand = (averagepersku['AverageInventory']/(df4['Stock']/15)))

In [69]:
DOH.sort_values(by=['DaysOnHand'], ascending=False)

,Stock,AverageInventory,DaysOnHand
sku,,,
كارت فودافون - 4.25 جنية,16,386.5,362.343750
شاي ليبتون اخضر بالنعناع (عرض) - 25 فتلة,6,142.5,356.250000
فيبا ليمون +600 جرام هدية - 4 لتر,27,267.0,148.333333
سائل اطباق بريل متكرر - 35 جرام,16,154.5,144.843750
شاى ليبتون أخضر بدون مرارة (عرض) - 25 فتلة,12,88.0,110.000000
...,...,...,...
بسكويت ساده بسكو ماكس - 2 جنية,7443,3733.0,7.523176
زيت خليط زيزينيا - 900 مل,2546,1276.5,7.520621
شاي ليبتون عرض - 25 فتلة,12400,6214.5,7.517540
فول فودى مدمس سادة - 400 جرام,4938,2473.0,7.512151
شويبس جولد أناناس - 1 لتر,1010,505.5,7.507426